### ISSUE TITLE
Add Google Cloud Storage Repository

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-gce#11]
We want to have Snapshot and Restore available for Google Storage Repository.

**Comment by rvrignaud** [comment]
+1 would be a great feature !

**Comment by vvasanth86** [comment]
Would this be available soon? Thanks!

**Comment by pires** [comment]
+1

**Comment by thekantian** [comment]
What's blocking getting this in? Just spun up an ES cluster in GCE and right now I have 2 choices for backup (I think):

1) rsync files to GCS (the old way of backups, don't get any of the snapshot/restore goodies
2) set up NFS shared folder on all machines and use as a target (tons of overhead that I don't want to deal with).

Given that GCS exists, would be a much better option... What's the roadmap for getting this merged? - 6 months seems like a long time to review...I'm happy to help with whatever work needs to be done!

**Comment by tlrx** [comment]
@thekantian I apologize for the time it takes but be sure it's still on the road. Some internal classes in elasticsearch have changed multiple times the last few months, making this difficult to test and merge. Now things are stabilized it should not take too much time to be merged.

**Comment by thekantian** [comment]
No apology necessary! Thanks for the update - I was just wondering if there was anything I could do to help move it along since I'm sure it will improve the Google Cloud platform experience for ES a lot for us all!

**Comment by pires** [comment]
Great news :+1:

**Comment by hussein-vastani** [comment]
+1 
Hoping to see this land soon! My current GCE project has a dependency on this. Thank you.

**Comment by soundofjw** [comment]
Who do we buy :beers: for to see this completed? @tlrx ? :)

**Comment by simonmorley** [comment]
+1

**Comment by ipinatti-ciandt** [comment]
+1 !

**Comment by akleiman** [comment]
+1

**Comment by fvantin** [comment]
+1

**Comment by MaxDaten** [comment]
+1

**Comment by psychonaut** [comment]
+1

**Comment by vishalshah-org** [comment]
any updates on this, we are paying big time $$ to backup to S3 from our google cloud infrastructure :( any help appreciated!
thanks.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#12880

**Comment by tlrx** [comment]
A plugin for Google Cloud Storage has just been merged into master (see elastic/elasticsearch/pull/13578) and will be released with the next version of Elasticsearch.

**Comment by speedplane** [comment]
@tlrx Any chance this plugin will be backported to `1.x`? I'd like to use this feature to backup my index before upgrading to `2.x`.

**Comment by tlrx** [comment]
> @tlrx Any chance this plugin will be backported to 1.x?

@speedplane Unfortunately no, I don't plan to do it. This would require a lot of work :( I suggest to use a different way to backup your data before upgrading (snapshot on `fs` or `s3`).

**Comment by psychonaut** [comment]
@speedplane S3 compatibility interface in GCS is more or less usable, it will be fine for backup.

**Comment by apierleoni** [comment]
@tlrx Is this plugin targeting elasticsearch 5? or will it work in  >2.4 as well? cc/ @elipapa

**Comment by tlrx** [comment]
@apierleoni A `repository-gcs` plugin has been developed for 5.x (see https://github.com/elastic/elasticsearch/pull/13578) and it won't be backported to 2.x.

**Comment by apierleoni** [comment]
@tlrx thanks for the clarification.

**Comment by shahsaifi** [comment]
any documentation link to set-up and enable snapshots to GCS will be highly appreciated.  Official documentation of 5.x explains about installing the plug-in but couldn't get any of the doc simplifying gcs bucket and config part similar to S3.
