### ISSUE TITLE
Frequent MasterNotDiscoveredException exceptions

### ISSUE THREAD

**Issue by barakcoh** [elastic/elasticsearch-cloud-gce#42]
Hi

We're running a 3 node test cluster on GCE. Master node is stable and replies quickly to queries. Non-master nodes respond properly only for an hour or so and then most requests return a `MasterNotDiscoveredException` exception. 

Logs show the slaves are trying to ping the correct master but don't get any response. Minimum number of master-eligible nodes is 2. The ElasticSearch VMs have proper tags to ensure they don't go off pinging irrelevant VMs in the GCE project.

Not sure if the GCE connector is the root cause here, but we can't seem to find another explanation.

**Comment by dadoonet** [comment]
Hi @barakcoh 

Sorry for looking at this lately.
I wonder if this error message disappear at some point or if you are forced to restart the node as soon as you get such a message.

**Comment by barakcoh** [comment]
@dadoonet no worries. It appears I misread the documentation or it's not clear enough. I only allowed nodes to communicate over ports 9200 and 9300, not realizing ES would ping on other ports as well which caused it to think other nodes are not alive. Once I opened other ports everything worked fine.

**Comment by dadoonet** [comment]
\o/ thanks for your answer! :)
