### ISSUE TITLE
IllegalStateException on Boot.

### ISSUE THREAD

**Issue by Poogles** [elastic/elasticsearch-cloud-gce#45]
Having some problems getting instances to start with this plugin.  When the following config is added;

cluster.name: infectes
node.master: true
node.data: true
cloud:
  gce:
      project_id: infectiousearch
      zone: ["europe-west1-b", "europe-west1-c", "europe-west1-d"]
discovery:
      type: gce

They refuse to start with the following error;

[2015-02-23 17:54:32,831][INFO ][node                     ] [Scintilla] version[1.4.4], pid[16126], build[c88f77f/2015-02-19T13:05:36Z]
[2015-02-23 17:54:32,831][INFO ][node                     ] [Scintilla] initializing ...
[2015-02-23 17:54:32,847][INFO ][plugins                  ] [Scintilla] loaded [cloud-gce], sites []
[2015-02-23 17:54:35,891][ERROR][bootstrap                ] {1.4.4}: Initialization Failed ...
1) NoSuchMethodError[org.elasticsearch.discovery.zen.ZenDiscovery.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/cluster/ClusterName;Lorg/elasticsearch/threadpool/ThreadPool;Lorg/elasticsearch/transport/TransportService;Lorg/elasticsearch/cluster/ClusterService;Lorg/elasticsearch/node/settings/NodeSettingsService;Lorg/elasticsearch/cluster/node/DiscoveryNodeService;Lorg/elasticsearch/discovery/zen/ping/ZenPingService;Lorg/elasticsearch/Version;Lorg/elasticsearch/discovery/DiscoverySettings;)V]2) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]

Seems similar to;  http://elasticsearch-users.115913.n3.nabble.com/Connection-problems-on-Amazon-EC2-td4020001.html

Versioning is as follows;

dpkg -l | grep elastics && dpkg -l | grep openjdk
ii  elasticsearch                             1.4.4                         all          Open Source, Distributed, RESTful Search Engine
ii  openjdk-7-jre-headless:amd64              7u75-2.5.4-1~deb7u1           amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

**Comment by dadoonet** [comment]
@Poogles Sorry answering late. Which version of GCE plugin are you using? `2.4.1` or `2.4.0`?

**Comment by dadoonet** [comment]
I guess it was solved in the meantime. Closing. Feel free to reopen if you have any more information.
