### ISSUE TITLE
Remove component settings from AbstractComponent

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-gce#50]
Related to elasticsearch/elasticsearch#9919

**Comment by schonfeld** [comment]
hey @dadoonet ... pretty sure removing all that logic from GceDiscovery.java broke this plugin's ability to discover other elasticsearch nodes on GCE... see issues #53 & #54.

**Comment by dianat-porch** [comment]
Having problems with ES 1.7.1 and plugin 2.7.0 as well.  Nodes aren't discovering each other.  @schonfeld could it be related?

**Comment by schonfeld** [comment]
@dianat-porch most likely, this is the cause. We're using v2.5.0 w/ ES 1.7. Works just fine... For now :)

**Comment by hagait** [comment]
Thanks @schonfeld, It seems to work fine with v2.5.0 and ES 1.7.1.
