### ISSUE TITLE
No hosts discovered

### ISSUE THREAD

**Issue by skauk** [elastic/elasticsearch-cloud-gce#58]
I need to setup a cluster on GCE for a legacy system which requires version 1.7.
I've setup two instances and installed the plugin according to docs but they don't see each other.
All I see in logs (set to TRACE) is this:

> [2018-01-12 14:06:42,696][TRACE][discovery.gce ] [Gravity] starting to ping
> [2018-01-12 14:06:45,697][TRACE][discovery.gce ] [Gravity] full ping responses: {none}
> [2018-01-12 14:06:45,697][DEBUG][discovery.gce ] [Gravity] filtered ping responses: (filter_client[true], filter_data[false]) {none}

Any suggestions on what could be wrong?

**Comment by dadoonet** [comment]
Version 1.7 is not maintained anymore.
May be ask this question on discuss.elastic.co?
